version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db
    command: -p 5433
    expose:
      - 5433
    restart: always
    env_file:
      - questions/.env-non-dev
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: redis
    command: --port 6379
    expose:
      - 6379
    networks:
      - custom
  fastapi_app:
    build:
      context: ./questions/.
    env_file:
      - questions/.env-non-dev
    container_name: fastapi_app
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - custom
    depends_on:
      - db
      - redis
  bot:
    restart: on-failure
    build:
      context: tg-bot
      dockerfile: Dockerfile
    container_name: "bot"
    env_file:
      - ./tg-bot/.env-non-dev
    networks:
      - custom
    command: python src/app.py
networks:
  custom:
    driver: bridge
volumes:
  db-data: